### ISSUE TITLE
any<blade> does not work

### ISSUE THREAD

**Issue by CowHunter0** [CowHunter0/wizsprinter#9]
when trying with this config

`any<blade>[sharpen] @ self | any<blade> @ self | any<blade>[sharpen] @ michael | any<blade> @ michael`

blades are ignored and the client passes instead.  I tried with both a basic school blade and an elemental blade, and neither work.

other "any" commands work, such as any<trap>.

**Comment by KawhiNot** [comment]
close this issue

**Comment by CowHunter0** [comment]
Fixed.  any<blade> configs were incorrectly selecting spells that modify incoming damage (shields) instead of spells that modify your outgoing damage (blades)
